name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have a great idea for Gemini Audio MCP? Let us know!
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
      description: What should the feature do?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature useful?
    validations:
      required: true
